sources:
  - https://feeds.feedburner.com/PythonSoftwareFoundationNews
  - https://realpython.com/atom.xml?format=xml
  - https://pyimagesearch.com/feed
  - https://planetpython.org/rss20.xml
  - https://pbpython.com/feeds/all.atom.xml
  - https://blog.jetbrains.com/pycharm/feed
  - https://devblogs.microsoft.com/python/feed
top_n: 5
threshold: 0.15
language: english